version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_install:
      - pip install Cython==0.29.23 numpy==1.20.3

sphinx:
   configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs